apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base

helmCharts:
- name: trino
  namespace: trino
  releaseName: trino
  repo: https://trinodb.github.io/charts
  valuesFile: values-dev.yaml
  version: 1.39.1
