apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trino

commonAnnotations:
  owner: kcl

resources:
- namespace.yaml

helmCharts:
- name: trino
  namespace: trino
  releaseName: trino
  repo: https://trinodb.github.io/charts
  valuesFile: values.yaml
  version: 1.39.1

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: trino
    app.kubernetes.io/part-of: lakehouse
